// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpJ66X-tFv3_ncs7Ww6I0famOFKI7BC_o',
    appId: '1:127631882515:web:f4aeb7810990c6642e02e6',
    messagingSenderId: '127631882515',
    projectId: 'poker-first-5f294',
    authDomain: 'poker-first-5f294.firebaseapp.com',
    storageBucket: 'poker-first-5f294.firebasestorage.app',
    measurementId: 'G-SZ5GN5ZZ8L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYhXAbSYBGAyd2bs3cDII2Yx7VoCD5Fm0',
    appId: '1:127631882515:android:24c9010612db5f452e02e6',
    messagingSenderId: '127631882515',
    projectId: 'poker-first-5f294',
    storageBucket: 'poker-first-5f294.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU28oHxH0Wa5VGnpKgnE5TEixNjfcxz6M',
    appId: '1:127631882515:ios:9fc196ae0ccb769f2e02e6',
    messagingSenderId: '127631882515',
    projectId: 'poker-first-5f294',
    storageBucket: 'poker-first-5f294.firebasestorage.app',
    iosBundleId: 'com.realapp.pokerFirst',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU28oHxH0Wa5VGnpKgnE5TEixNjfcxz6M',
    appId: '1:127631882515:ios:9fc196ae0ccb769f2e02e6',
    messagingSenderId: '127631882515',
    projectId: 'poker-first-5f294',
    storageBucket: 'poker-first-5f294.firebasestorage.app',
    iosBundleId: 'com.realapp.pokerFirst',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpJ66X-tFv3_ncs7Ww6I0famOFKI7BC_o',
    appId: '1:127631882515:web:691fd125935700c82e02e6',
    messagingSenderId: '127631882515',
    projectId: 'poker-first-5f294',
    authDomain: 'poker-first-5f294.firebaseapp.com',
    storageBucket: 'poker-first-5f294.firebasestorage.app',
    measurementId: 'G-JX3R911LZL',
  );
}
